# paths to include during linting
included:
  - Sources/
# paths to exclude during linting
excluded:
  - Pods
  - Carthage
  - MaterialUIExamples
  - MaterialUITests
opt_in_rules:
  - file_name
  - sorted_imports
  - opening_brace
  - closing_brace
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - let_var_whitespace
  - modifier_order
  - no_extension_access_modifier
  - no_fallthrough_only
  - object_literal
  - number_separator
  - unused_import
  - unused_declaration
  - indentation_width
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - explicit_self
  - fallthrough
  - fatal_error_message

indentation_width:
  severity: error
  indentation_width: 4
  include_comments: true

type_body_length:
  warning: 800
  error: 1200

line_length:
  warning: 101
  error: 120
  ignores_urls: true
  ignores_comments: true
